### ISSUE TITLE
Check for pathlist file

### ISSUE THREAD

**Issue by mobeets** [mobeets/mpm#22]
After downloading, check for a file `pathlist.m` (or something like `mpmpaths.m`) containing a list of folders to add to path (see #20 ). This would override the default action.

**Comment by tsdev** [comment]
The question is what format should the file have. What I would do is to call it `pathlist` (even without extension) that is just plain text with each line describes a relative path from the root folder of the package:
```
bin/class1
bin/class2
bin
etc/*
```
Lines that end with * would mean to add all subdirectories `addpath(genpath([packagePath filesep 'etc']))`, any other line would just define a single folder. To make it Windows/Linux/MacOs compatible the file could use either `/` or `\` and it would  be exchanged automatically in the `addpath()` calls, depending on the system `mpm` runs.

**Comment by mobeets** [comment]
Yeah sounds good. So I'm guessing this is the file that `mpm on` and `mpm off` will handle, where `mpm on` calls `addpath` for everything in here, and `mpmoff` calls `rmpath`.

**Comment by mobeets** [comment]
Added function in https://github.com/mobeets/mpm/commit/5abf62a4560ed8a4a8b39573c2ce320b5f1daa47 that will now return a path ready for adding/removing.

```
pathfile = fullfile(pkg.installdir, pkg.mdir, 'pathlist.m')
pkgbasedir = fullfile(pkg.installdir, pkg.mdir)
checkForPathlistAndGenpath(pathfile, pkgbasedir)
```

This is not yet called anywhere. E.g., when adding paths, we should probably add these.

**Comment by mobeets** [comment]
Fixed in https://github.com/mobeets/mpm/commit/ae49c0e3683839aaa49609b4c73c7604514f025e
