### ISSUE TITLE
Replace python backend with matlab

### ISSUE THREAD

**Issue by mobeets** [mobeets/mpm#23]
matlab has built-ins for downloading and extracting: `unzip`, `websave`, etc. (see #20 )

**Comment by wrgrant** [comment]
For those interested in contributing, could you give a brief overview of where to start with this issue? What files to look in? Maybe edit into the description a running checklist of functions to implement?

**Comment by mobeets** [comment]
Yes, that would be great! I've made a milestone [here](https://github.com/mobeets/mpm/milestone/1) with what I think are all the relevant to-dos, so I'll close this issue.
