### ISSUE TITLE
Github API search

### ISSUE THREAD

**Issue by octomike** [mobeets/mpm#42]
I'm a little confused by what `mpm install foo -g` actually searches for. When I use it, I rarely get useful results.

The constructed  query is:

```
/?q=foo&language=matlab&sort=stars&order=desc
```

I believe the "best" query, according to the API  should be:

```
/?q=foo+language:matlab
```

The problem here unfortunately is, that `webread()` will encode the `:` and `+` sign, which foobars the search results completely.

**Comment by bendichter** [comment]
@mobeets close this?
