### ISSUE TITLE
mpm -e

### ISSUE THREAD

**Issue by bendichter** [mobeets/mpm#46]
One of my favorite features of `pip` is the `-e` mode. This mode can be used on a package that is installed from a local directory and instead of copying these files into an `mpm-packages` directory, creates a link in `mpm-packages` to the package. The advantage of this is you can edit the package in its current location. In the end, the effect is very similar to a simple `addpath(genpath(dir));` but it gathers requirements for this package and allows `mpm` to keep track of this dependency and leverage the other enhancements (uninstall, environments, `install.m`, etc.)

**Comment by mobeets** [comment]
Oh cool, yeah I like this idea too

**Comment by mobeets** [comment]
Or maybe a better way of thinking about this is that `mpm install -e` does the same thing that `mpm install` does, except it doesn't download anything from a url. So this is probably just a few extra lines in `findAndSetupPackage()`.

**Comment by bendichter** [comment]
Yes that's right it would be `mpm install -e path/to/package`.

The way `pip` works is you can call `pip install path/to/package` (usually `pip install .`). This installs any local package, but in non-delevoper mode, meaning the package is copied to a directory in `site-packages` with all the other packages that have been downloaded from pypi. A package installed in this way is not meant to be edited after installation. If you do a local install (directing `pip` to a local directory as opposed to the name of a remote package on pypi) you also have the option to install in developer mode (`pip install -e path/to/package`). This will not copy the directory to site-packages, but instead create a link from site-packages to the current `path/to/package`. Now you can develop the code in its current place. I suggest implementing both of these features, the install from a local directory, and the option to install in developer mode.

**Comment by mobeets** [comment]
Great, makes sense!
