### ISSUE TITLE
local install empty dir

### ISSUE THREAD

**Issue by bendichter** [mobeets/mpm#53]
```
$ git clone https://github.com/michael-zugaro/FMAToolbox.git
>> mpm install FMAToolbox -u /Users/bendichter/dev/FMAToolbox --local --force
```

puts an _empty_ FMAToolbox folder in `mpm-packages`

**Comment by mobeets** [comment]
Thanks for reporting all of these! Should be working now--stupid bug on my part when using copyfile.

**Comment by bendichter** [comment]
fix confirmed. Thanks!
