### ISSUE TITLE
paths added by default

### ISSUE THREAD

**Issue by bendichter** [mobeets/mpm#54]
What's the motivation for looking for folders called 'bin', 'src', 'lib', or 'code'? My preference would be to have the default behavior be adding all folders (i.e. `addpath(genpath(path/to/toolbox))`), which you can override with a set of paths. In the correct configuration, I'm having trouble properly installing some packages, like [FMAToolbox](https://github.com/michael-zugaro/FMAToolbox)

**Comment by mobeets** [comment]
The idea was just to not flood the user path with every possible folder, but yeah, I see your point that for certain packages you do want most or all folders added.

I will add a flag that says to just add all folders in a package to the path. Would that work?

**Comment by mobeets** [comment]
Something like `mpm install FMAToolbox -u /Users/mobeets/code/FMAToolbox --local --allpaths` should work now

**Comment by bendichter** [comment]
Works. Thanks!
