### ISSUE TITLE
install not adding paths?

### ISSUE THREAD

**Issue by bendichter** [mobeets/mpm#57]
I might be doing something wrong here... when I run `>> mpm install buzcode -u https://github.com/bendichter/buzcode` I only see buzcode in mpm-packages, and the directory is empty.

**Comment by mobeets** [comment]
Adding `.git` to the end of the url made it work for me. I got this error when I tried it without:

```
>> mpm install buzcode -u https://github.com/bendichter/buzcode
Collecting 'buzcode'...
   Downloading https://github.com/bendichter/buzcode...
Warning: If you were trying to install a github repo, try
adding ".git" to the end. 
```

**Comment by bendichter** [comment]
woops my bad.
