### ISSUE TITLE
Using --force on requirements.txt still prompts for confirmation

### ISSUE THREAD

**Issue by dhoer** [mobeets/mpm#66]
Using `--force` on requirements.txt still prompts for confirmation
```
>> mpm install -i /matlab/requirements.txt --force        
Using collection "default"
About to run the following commands: 
   mpm install export_fig -u http://www.mathworks.com/matlabcentral/fileexchange/23629-export-fig -d /mpm/mpm-packages -c default --force
   mpm install matlab2tikz -t 1.0.0 -d /mpm/mpm-packages -c default --force
   mpm install colorbrewer -d /mpm/mpm-packages -c default --force
Confirm (y/n)? 
```

Would expect this to not prompt for confirm when using force flag. Breaks automation.

**Comment by mobeets** [comment]
Great point, I don't think I've handled the `--force` argument correctly when installing via requirements.txt.

**Comment by dhoer** [comment]
Would another flag, in this case, be needed?  I'm think about how terraform has a flag auto approve to approve its provisioning plan: https://www.terraform.io/docs/commands/apply.html#auto-approve

**Comment by mobeets** [comment]
Yeah good suggestion, added flag `--approve` (which can only be used when providing `-i`).
