### ISSUE TITLE
Directory path in packages file gets ignored

### ISSUE THREAD

**Issue by dhoer** [mobeets/mpm#71]
So requirements.txt with line `colorbrewer -d /matlab`:

    export_fig -u http://www.mathworks.com/matlabcentral/fileexchange/23629-export-fig 
    matlab2tikz -t 1.0.0
    colorbrewer -d /matlab

Would get rewritten as `mpm install colorbrewer -d /matlab -d /home/matlab/mpm/mpm-packages -c default`:

    >> mpm install -i requirements.txt
    Using collection "default"
    About to run the following commands: 
       mpm install export_fig -u http://www.mathworks.com/matlabcentral/fileexchange/23629-export-fig -d /home/matlab/mpm/mpm-packages -c default
       mpm install matlab2tikz -t 1.0.0 -d /home/matlab/mpm/mpm-packages -c default
       mpm install colorbrewer -d /matlab -d /home/matlab/mpm/mpm-packages -c default
    Confirm (y/n)? 

Ignoring the path of `/matlab/colorbrewer`:

    Updating paths...
       Adding to path: /home/matlab/mpm/mpm-packages/colorbrewer

**Comment by mobeets** [comment]
Yeah good find! Should be straightforward to fix. I'll just need to add some extra cases to `readRequirementsFile()`, to ensure that if `-d` is provided (or `-c` as well) inside requirements.txt, you cannot say something like `mpm install -i requirements.txt -d example`.
