### ISSUE TITLE
`mpm search surf2stl` not working

### ISSUE THREAD

**Issue by 4086606** [mobeets/mpm#75]
@mobeets wanna use this in a new package. I presume the File Exchange has updated the DOM. It would be better to just use [`htmlTree`](https://uk.mathworks.com/help/textanalytics/ref/htmltree.findelement.html) with a sturdy selector such as `h3 a[href^="/matlabcentral/fileexchange"]`.

**Comment by mobeets** [comment]
Should be working now! htmlTree would work, but it wasn't introduced until 2018 so I want to make sure this still works for older versions. So I just updated the regex.

**Comment by 4086606** [comment]
I'd suggest using htmlTree if it's available because it'll be more sturdy. Progressive enhancement.

Also would you like to have Git-style CLI options? I have a local branch ready to go for this:

```matlab
% To modify the default behavior of the above commands,
% the following optional arguments are available: 
%
% name-value arguments:
%   url (-u): optional; if does not exist, must search
%   in-file (-i): if set, will run mpm on all packages listed in file
%   install-dir (-d): where to install package
%   query (-q): if name is different than query
%   release-tag (-t): if url is found on github, this lets user set release tag
%   internal-dir (-n): lets user set which directories inside package to add to path
%   collection (-c): override mpm's default package collection ("default")
%   by specifying a custom collection name
%
% arguments that are true if passed (otherwise they are false):
%   --github-first (-gh): check github for url before matlab fileexchange
%   --force (-f): install package even if name already exists in InstallDir
%   --approve: when using -i, auto-approve the installation without confirming
%   --debug: do not install anything or update paths; just pretend
%   --no-paths: no paths are added after installing (default if -c is specified)
%   --all-paths: add path to all subfolders in package
%   --local: url is a path to a local directory to install (add '-e' to not copy)
```

**Comment by mobeets** [comment]
I don't actually have 2018+ so I can't really test it myself.
What do you mean by Git-style CLI options?

**Comment by 4086606** [comment]
The options would use `--kebab-case` instead of `--snake_case`, which is really common for CLIs in other languages. Also necessitates a switch to `opts.camelCase` for fields in the mpm function

**Comment by 4086606** [comment]
> I don't actually have 2018+ so I can't really test it myself.
I'll set it up and test it, I have Matlab Online

**Comment by 4086606** [comment]
So should I open a PR with these two changes?

**Comment by mobeets** [comment]
Yeah sure that would be great!
