### ISSUE TITLE
Document version requirements?

### ISSUE THREAD

**Issue by apjanke** [mobeets/mpm#79]
Hi! I'm interested in using and maybe contributing to this package.

Would you mind documenting which versions of Matlab it supports/requires, so I know where I can run it, and which level of language features I can use if I make a PR to this repo? And does it support all the OSes that Matlab currently runs on?

Cheers,
Andrew

**Comment by mobeets** [comment]
Hi, great question! As far as I know, this code should work cross-platform on any Matlab version 2014b and later. (`webread` was introduced in 2014b, which I think is the most recently added function it needs.) I haven't run it _recently_ on windows/linux but I don't see why it shouldn't work there. Let me know if you come across any issues!

**Comment by mobeets** [comment]
(Added version requirements to the Readme.)

**Comment by apjanke** [comment]
Cool, thanks!
