### ISSUE TITLE
MATLAB Products not supported by MPM

### ISSUE THREAD

**Issue by nmerlene** [mobeets/mpm#80]
Hi,

I've been using MPM for a few months now and it works great, with the only exception being that there's a few products it doesn't seem to support yet:

```
#6 5.778 Installing with the following parameters:
#6 5.778 --destination=/opt/matlab
#6 5.778 --release=r2021b
#6 5.778 --products=MATLAB MATLAB_Coder DO_Qualification_Kit Simulink Simulink_Coder Simulink_Design_Verifier Simulink_Check Simulink_Test Simulink_Code_Inspector Simulink_Coverage
#6 5.778 ---------------------------------------------
#6 9.371 Error: Unable to install these products because they are not supported by MPM:
#6 9.371 DO_Qualification_Kit
#6 9.371 Simulink_Code_Inspector
```

Is there any plan (or would it be possible) to add support for the `DO Qualification Kit` and `Simulink Code Inspector` products in the near future?  My initial assumption was that MPM would be able to install any product *not* listed under [Products Not Available for Linux](https://www.mathworks.com/support/requirements/system-requirements-linux.html).

**Comment by mobeets** [comment]
I think you have the wrong "mpm." This code isn't associated at all with the one [here](https://github.com/mathworks-ref-arch/matlab-dockerfile), as far as I'm aware!
