### ISSUE TITLE
Name conflict with MATLAB's official "MATLAB Package Manager"

### ISSUE THREAD

**Issue by tvannoy** [mobeets/mpm#81]
MATLAB's built-in package manager is named the same as this repo's `mpm`, resulting in this warning:
```
Warning: Function mpm has the same name as a MATLAB builtin. We suggest you rename the function to avoid a potential name conflict.
```
MATLAB's package manager appears to only be for Mathwork's products. 

This isn't currently an issue for me, as I'm not using MATLAB's mpm. However, I could see using both package managers being useful; for example, I could use MATLAB's mpm to build a containerized version of MATLAB, then, after that, I would use this repo's mpm to install community packages per usual.

@mobeets What are your thoughts on this name conflict? Perhaps the name conflict is inconsequential and we can use both yours and MATLAB's mpm together without issues. 

MATLAB's mpm is included as a toolbox in R2022b (toolbox/matlab/mpm).

**Comment by mobeets** [comment]
Hm, that's interesting, thanks for letting me know! Bummer they used the same name/command.

Maybe in the absence of specific bugs people are running into, for now I'll just put a warning in the README.
