### ISSUE TITLE
mpm in conflict with Matlab's own functions

### ISSUE THREAD

**Issue by BJCaasenbrood** [mobeets/mpm#82]
He, 

Just gave mpm a shot, and with works phenomenal. Unfortunatelly, i had to rename the 'mpm'->'pip' to make it work, since mpm is an embedded function within Matlab since 2022b release.

Its a pity....

**Comment by mobeets** [comment]
Thanks, glad it works well for you! Can you explain what didn't work before you renamed it? On my version it's just a warning message, but mpm itself works just fine.

**Comment by BJCaasenbrood** [comment]
He @mobeets,

Thanks for the quick reply. After reading the documentation (better), I overlooked the mention of this issue (my bad). I am currently running Matlab 2023b (64-bit Linux platform), and installed `mpm` via the Add-On manager. Running the following code `mpm freeze`, it returns.

```
Warning: Function mpm has the same name as a MATLAB built-in. We suggest you rename the function to avoid a potential name conflict. 
Error using mpm
This command is not supported when the mpm feature is not enabled. Start MATLAB with the -mpm command line switch.
```

Matlab inherently overshadows `mpm` with its own built-in function. Using `which mpm -all` I indeed get:
```
built-in (/usr/local/MATLAB/R2023a/toolbox/matlab/mpm/mpm)
/home/..../MATLAB Add-Ons/Collections/mpm/mobeets-mpm-c626429/mpm.m  % Shadowed
``` 

Manually adding the "mobeets-mpm-c626429" folder to the Matlab's search path does seem to do the trick though. I'm not sure if this can be fixed via the Add-On manager alone...

**Comment by BJCaasenbrood** [comment]
I did a bit of research, but apparently you cannot overshadow built-in Matlab functions. Renaming `mpm` is unfortunately the only option.

**Comment by zm-cttae** [comment]
This awesome package needs a release tag if stable fwiw..

**Comment by BJCaasenbrood** [comment]
Fully agree 👍

**Comment by zm-cttae** [comment]
I think `pim` rebrand, `Package Installer for MATLAB` would be appropriate. It's breaking but it gives latest version comlat

**Comment by mobeets** [comment]
Yeah I think that's the only solution sadly. Good suggestion for a new name, thank you.

I think I might go with Matlab Package Installer and mpi. That way it's only one character different from the current name.

**Comment by samimia-swks** [comment]
+1 for renaming this great little project. The annoying warnings aside, I just had a colleague that I had told about MPM download this by mistake https://github.com/mathworks-ref-arch/matlab-dockerfile/blob/main/MPM.md#windows

**Comment by mobeets** [comment]
Okay, changed the name to mpi and made a release.

Curious if anyone knows if changing the name of this repo (so that the url will contain `mpi` instead of `mpm`) will mess anything up? Ditto for on Mathworks.

**Comment by BJCaasenbrood** [comment]
Thanks for changing the name. A bit unfortunate timing from my end, recently published a paper explain the installation procedure using `mpm` instead of `mpi`. Nevertheless, thanks for addressing the bug.

Personally, I'd keep the repo name as is, simply to avoid breaking stuff. From my experience, the Matlab Exchange and Github repo do not pair well, I often have to manual fix stuff at the Matlab Exchange if I publish new versions of my code.

**Comment by mobeets** [comment]
Ah dang, sorry about that!
But yeah that makes sense, I'll just keep it as-is.

**Comment by BJCaasenbrood** [comment]
> Ah dang, sorry about that!
> But yeah that makes sense, I'll just keep it as-is.

Ah, it happens. No worries. It's a good lesson for future publications.
