### ISSUE TITLE
fails to install package: differential-evolution

### ISSUE THREAD

**Issue by samimia-swks** [mobeets/mpm#86]
Downloading this package results in an error with R2024b: 
https://www.mathworks.com/matlabcentral/fileexchange/18593-differential-evolution

```
>> mpi install differential-evolution -u https://www.mathworks.com/matlabcentral/fileexchange/18593-differential-evolution
Using collection 'default'.
Creating 'differential-evolution' collection.
Downloading 'https://www.mathworks.com/matlabcentral/fileexchange/18593-differential-evolution'.
Warning: Error downloading GitHub ZIP file. 
````

PS: the first google hit for this package is this page, which does not have a link to the github: https://mobeets.github.io/mpm/
So it is a bit difficult to know where to file issues.

**Comment by mobeets** [comment]
Hi, thanks for submitting an issue! This seems to be an issue on FileExchange's end. For most packages, appending `?download=true` to the package url returns a zip file. If you try to put `https://www.mathworks.com/matlabcentral/fileexchange/18593-differential-evolution?download=true` into a browser you get this error:

<img width="494" alt="Screenshot 2024-11-22 at 8 03 09 AM" src="https://github.com/user-attachments/assets/0aa6020b-51f7-49dd-8882-3715a5f6dcb0">

So unfortunately there's not much I can do in terms of simple fixes. Sorry about that.

Also thank you for the heads up about not linking to the github! I will fix that asap.
